version: '3.7'

services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: crud
      MYSQL_USER: crud
      MYSQL_PASSWORD: YffmtwhFuHzZ6ixHbCiy
      MYSQL_ROOT_PASSWORD: YffmtwhFuHzZ6ixHbCiy
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: { }
